apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pino-mongodb
spec:
  selector:
    matchLabels:
      name: pino-mongodb
  template:
    metadata:
      labels:
        name: pino-mongodb
    spec:
      containers:
      - name: pino-mongodb
        image: sungeunchoikr/k8s-pino-mongodb:1.0.0
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        env:
        - name: DB_URL
          value: '<DB_URL>'
        - name: DB_COLLECTION
          value: '<DB_COLLECTION>'
        - name: MATCH_PODS  # comma-separated list
          value: '<MATCH_PODS>'
      terminationGracePeriodSeconds: 5
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

